version: "3"

services:

    db:
        image: postgres:9.6
        restart: always
        environment:
            - POSTGRES_USER=birdsitelive
            - POSTGRES_PASSWORD=birdsitelive
            - POSTGRES_DB=birdsitelive
        volumes:
            - ./postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
